matrix:
  include:
  - os: linux
    dist: trusty

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

notifications:
  email: true

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.17.1
  - openssl aes-256-cbc -K $encrypted_c35b3785930d_key -iv $encrypted_c35b3785930d_iv
        -in org.travis-ci.enc -out ~/.ssh/org.travis-ci -d
  - chmod 600 ~/.ssh/org.travis-ci
  - echo -e "Host $DEPLOY_ADDRESS\n\tHostName $DEPLOY_ADDRESS\n\t
        StrictHostKeyChecking no\n\tIdentityFile ~/.ssh/org.travis-ci" >> ~/.ssh/config

#before_script:
#  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

addons:
  ssh_known_hosts: $DEPLOY_ADDRESS

install:
  - go mod tidy

script:
  - $GOPATH/bin/golangci-lint run
  - go test
  - go build -o travis-cd-new main.go

after_success:
  - scp -o stricthostkeychecking=no travis-cd-new Procfile
      $DEPLOY_USERNAME@$DEPLOY_ADDRESS:~/travis-ci-vps-cd/
  - ssh -tt $DEPLOY_USERNAME@$DEPLOY_ADDRESS < scripts/run.sh
