matrix:
  include:
  - os: linux
    dist: trusty

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

notifications:
  email: false

#before_script:
#  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

before_install:
  - openssl aes-256-cbc -K $encrypted_c35b3785930d_key -iv $encrypted_c35b3785930d_iv
        -in org.travis-ci.enc -out ~/.ssh/org.travis-ci -d
  - chmod 600 ~/.ssh/org.travis-ci
  - echo -e "Host $DEPLOY_ADDRESS\n\tHostName $DEPLOY_ADDRESS\n\t
        StrictHostKeyChecking no\n\tIdentityFile ~/.ssh/org.travis-ci" >> ~/.ssh/config

addons:
  ssh_known_hosts: $DEPLOY_ADDRESS

install:
  - go mod tidy

script:
  - go build -o travis-vps-test ./src/main.go

after_success:
  - scp -o stricthostkeychecking=no -r travis-vps-test
      $DEPLOY_USERNAME@$DEPLOY_ADDRESS:~/travis-vps-test/
  - ssh -tt $DEPLOY_USERNAME@$DEPLOY_ADDRESS < run.sh
