matrix:
  include:
  - os: linux
    dist: trusty

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

notifications:
  email: false

addons:
  ssh_known_hosts: $DEPLOY_ADDRESS

#before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

before_install:
  - openssl aes-256-cbc -K $encrypted_c35b3785930d_key -iv $encrypted_c35b3785930d_iv
    -in org.travis-ci.enc -out ~/.ssh/org.travis-ci -d
  - chmod 600 ~/.ssh/org.travis-ci

install:
  - go mod tidy

script:
  - cd src && go build

after_success:
  - ssh $DEPLOY_USERNAME@$DEPLOY_ADDRESS -o StrictHostKeyChecking=no
      'cd ~/test && mkdir travis && cp src'
  - scp -i ~/.ssh/org.travis-ci -o stricthostkeychecking=no -r ./src $DEPLOY_USERNAME@$DEPLOY_ADDRESS:~/test
